package pending_review

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
)

func parsePullRequestJSON(t *testing.T, str string) *PullRequest {
	var pr *PullRequest

	if err := json.Unmarshal([]byte(str), &pr); err != nil {
		t.Fatal("Unable to parse JSON")
	}

	return pr
}

func TestProcessLabelsNone(t *testing.T) {
	pr := parsePullRequestJSON(t, `{
		"url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12078",
		"id": 1018875423,
		"node_id": "PR_kwDODDMJAM48us4f",
		"html_url": "https://github.com/conan-io/conan-center-index/pull/12078",
		"diff_url": "https://github.com/conan-io/conan-center-index/pull/12078.diff",
		"patch_url": "https://github.com/conan-io/conan-center-index/pull/12078.patch",
		"issue_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/12078",
		"number": 12078,
		"state": "open",
		"locked": false,
		"title": "sqlite3: cross-compatibility conan v1 & v2",
		"user": {
		  "login": "SpaceIm",
		  "id": 30052553,
		  "node_id": "MDQ6VXNlcjMwMDUyNTUz",
		  "avatar_url": "https://avatars.githubusercontent.com/u/30052553?v=4",
		  "gravatar_id": "",
		  "url": "https://api.github.com/users/SpaceIm",
		  "html_url": "https://github.com/SpaceIm",
		  "followers_url": "https://api.github.com/users/SpaceIm/followers",
		  "following_url": "https://api.github.com/users/SpaceIm/following{/other_user}",
		  "gists_url": "https://api.github.com/users/SpaceIm/gists{/gist_id}",
		  "starred_url": "https://api.github.com/users/SpaceIm/starred{/owner}{/repo}",
		  "subscriptions_url": "https://api.github.com/users/SpaceIm/subscriptions",
		  "organizations_url": "https://api.github.com/users/SpaceIm/orgs",
		  "repos_url": "https://api.github.com/users/SpaceIm/repos",
		  "events_url": "https://api.github.com/users/SpaceIm/events{/privacy}",
		  "received_events_url": "https://api.github.com/users/SpaceIm/received_events",
		  "type": "User",
		  "site_admin": false
		},
		"body": "Specify library name and version:  **lib/1.0**\r\n\r\nThis is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!\r\n\r\n---\r\n\r\n- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.\r\n- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.\r\n- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.\r\n- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.\r\n",
		"created_at": "2022-08-05T16:48:05Z",
		"updated_at": "2022-08-06T10:14:44Z",
		"closed_at": null,
		"merged_at": null,
		"merge_commit_sha": "d314b77b026d284ad3ba8e2e304d0a4167ad85bc",
		"assignee": null,
		"assignees": [
	  
		],
		"requested_reviewers": [
	  
		],
		"requested_teams": [
	  
		],
		"labels": [
	  
		],
		"milestone": null,
		"draft": false,
		"commits_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12078/commits",
		"review_comments_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12078/comments",
		"review_comment_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/comments{/number}",
		"comments_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/12078/comments",
		"statuses_url": "https://api.github.com/repos/conan-io/conan-center-index/statuses/a21b42a345ce516a7d166101af78f6c5b1e156cf",
		"head": {
		  "label": "SpaceIm:sqlite3-conan-v2",
		  "ref": "sqlite3-conan-v2",
		  "sha": "a21b42a345ce516a7d166101af78f6c5b1e156cf",
		  "user": {
			"login": "SpaceIm",
			"id": 30052553,
			"node_id": "MDQ6VXNlcjMwMDUyNTUz",
			"avatar_url": "https://avatars.githubusercontent.com/u/30052553?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/SpaceIm",
			"html_url": "https://github.com/SpaceIm",
			"followers_url": "https://api.github.com/users/SpaceIm/followers",
			"following_url": "https://api.github.com/users/SpaceIm/following{/other_user}",
			"gists_url": "https://api.github.com/users/SpaceIm/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/SpaceIm/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/SpaceIm/subscriptions",
			"organizations_url": "https://api.github.com/users/SpaceIm/orgs",
			"repos_url": "https://api.github.com/users/SpaceIm/repos",
			"events_url": "https://api.github.com/users/SpaceIm/events{/privacy}",
			"received_events_url": "https://api.github.com/users/SpaceIm/received_events",
			"type": "User",
			"site_admin": false
		  },
		  "repo": {
			"id": 229263186,
			"node_id": "MDEwOlJlcG9zaXRvcnkyMjkyNjMxODY=",
			"name": "conan-center-index",
			"full_name": "SpaceIm/conan-center-index",
			"private": false,
			"owner": {
			  "login": "SpaceIm",
			  "id": 30052553,
			  "node_id": "MDQ6VXNlcjMwMDUyNTUz",
			  "avatar_url": "https://avatars.githubusercontent.com/u/30052553?v=4",
			  "gravatar_id": "",
			  "url": "https://api.github.com/users/SpaceIm",
			  "html_url": "https://github.com/SpaceIm",
			  "followers_url": "https://api.github.com/users/SpaceIm/followers",
			  "following_url": "https://api.github.com/users/SpaceIm/following{/other_user}",
			  "gists_url": "https://api.github.com/users/SpaceIm/gists{/gist_id}",
			  "starred_url": "https://api.github.com/users/SpaceIm/starred{/owner}{/repo}",
			  "subscriptions_url": "https://api.github.com/users/SpaceIm/subscriptions",
			  "organizations_url": "https://api.github.com/users/SpaceIm/orgs",
			  "repos_url": "https://api.github.com/users/SpaceIm/repos",
			  "events_url": "https://api.github.com/users/SpaceIm/events{/privacy}",
			  "received_events_url": "https://api.github.com/users/SpaceIm/received_events",
			  "type": "User",
			  "site_admin": false
			},
			"html_url": "https://github.com/SpaceIm/conan-center-index",
			"description": "Recipes for the conan-center repository",
			"fork": true,
			"url": "https://api.github.com/repos/SpaceIm/conan-center-index",
			"forks_url": "https://api.github.com/repos/SpaceIm/conan-center-index/forks",
			"keys_url": "https://api.github.com/repos/SpaceIm/conan-center-index/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/SpaceIm/conan-center-index/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/SpaceIm/conan-center-index/teams",
			"hooks_url": "https://api.github.com/repos/SpaceIm/conan-center-index/hooks",
			"issue_events_url": "https://api.github.com/repos/SpaceIm/conan-center-index/issues/events{/number}",
			"events_url": "https://api.github.com/repos/SpaceIm/conan-center-index/events",
			"assignees_url": "https://api.github.com/repos/SpaceIm/conan-center-index/assignees{/user}",
			"branches_url": "https://api.github.com/repos/SpaceIm/conan-center-index/branches{/branch}",
			"tags_url": "https://api.github.com/repos/SpaceIm/conan-center-index/tags",
			"blobs_url": "https://api.github.com/repos/SpaceIm/conan-center-index/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/SpaceIm/conan-center-index/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/SpaceIm/conan-center-index/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/SpaceIm/conan-center-index/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/SpaceIm/conan-center-index/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/SpaceIm/conan-center-index/languages",
			"stargazers_url": "https://api.github.com/repos/SpaceIm/conan-center-index/stargazers",
			"contributors_url": "https://api.github.com/repos/SpaceIm/conan-center-index/contributors",
			"subscribers_url": "https://api.github.com/repos/SpaceIm/conan-center-index/subscribers",
			"subscription_url": "https://api.github.com/repos/SpaceIm/conan-center-index/subscription",
			"commits_url": "https://api.github.com/repos/SpaceIm/conan-center-index/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/SpaceIm/conan-center-index/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/SpaceIm/conan-center-index/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/SpaceIm/conan-center-index/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/SpaceIm/conan-center-index/contents/{+path}",
			"compare_url": "https://api.github.com/repos/SpaceIm/conan-center-index/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/SpaceIm/conan-center-index/merges",
			"archive_url": "https://api.github.com/repos/SpaceIm/conan-center-index/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/SpaceIm/conan-center-index/downloads",
			"issues_url": "https://api.github.com/repos/SpaceIm/conan-center-index/issues{/number}",
			"pulls_url": "https://api.github.com/repos/SpaceIm/conan-center-index/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/SpaceIm/conan-center-index/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/SpaceIm/conan-center-index/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/SpaceIm/conan-center-index/labels{/name}",
			"releases_url": "https://api.github.com/repos/SpaceIm/conan-center-index/releases{/id}",
			"deployments_url": "https://api.github.com/repos/SpaceIm/conan-center-index/deployments",
			"created_at": "2019-12-20T12:43:32Z",
			"updated_at": "2022-01-11T00:46:56Z",
			"pushed_at": "2022-08-08T22:12:57Z",
			"git_url": "git://github.com/SpaceIm/conan-center-index.git",
			"ssh_url": "git@github.com:SpaceIm/conan-center-index.git",
			"clone_url": "https://github.com/SpaceIm/conan-center-index.git",
			"svn_url": "https://github.com/SpaceIm/conan-center-index",
			"homepage": "https://bintray.com/conan/conan-center",
			"size": 35041,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": "Python",
			"has_issues": false,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": {
			  "key": "mit",
			  "name": "MIT License",
			  "spdx_id": "MIT",
			  "url": "https://api.github.com/licenses/mit",
			  "node_id": "MDc6TGljZW5zZTEz"
			},
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
	  
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master"
		  }
		},
		"base": {
		  "label": "conan-io:master",
		  "ref": "master",
		  "sha": "7c3f81b16596a01e9d4785d98f996dd367901524",
		  "user": {
			"login": "conan-io",
			"id": 15212165,
			"node_id": "MDEyOk9yZ2FuaXphdGlvbjE1MjEyMTY1",
			"avatar_url": "https://avatars.githubusercontent.com/u/15212165?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/conan-io",
			"html_url": "https://github.com/conan-io",
			"followers_url": "https://api.github.com/users/conan-io/followers",
			"following_url": "https://api.github.com/users/conan-io/following{/other_user}",
			"gists_url": "https://api.github.com/users/conan-io/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/conan-io/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/conan-io/subscriptions",
			"organizations_url": "https://api.github.com/users/conan-io/orgs",
			"repos_url": "https://api.github.com/users/conan-io/repos",
			"events_url": "https://api.github.com/users/conan-io/events{/privacy}",
			"received_events_url": "https://api.github.com/users/conan-io/received_events",
			"type": "Organization",
			"site_admin": false
		  },
		  "repo": {
			"id": 204671232,
			"node_id": "MDEwOlJlcG9zaXRvcnkyMDQ2NzEyMzI=",
			"name": "conan-center-index",
			"full_name": "conan-io/conan-center-index",
			"private": false,
			"owner": {
			  "login": "conan-io",
			  "id": 15212165,
			  "node_id": "MDEyOk9yZ2FuaXphdGlvbjE1MjEyMTY1",
			  "avatar_url": "https://avatars.githubusercontent.com/u/15212165?v=4",
			  "gravatar_id": "",
			  "url": "https://api.github.com/users/conan-io",
			  "html_url": "https://github.com/conan-io",
			  "followers_url": "https://api.github.com/users/conan-io/followers",
			  "following_url": "https://api.github.com/users/conan-io/following{/other_user}",
			  "gists_url": "https://api.github.com/users/conan-io/gists{/gist_id}",
			  "starred_url": "https://api.github.com/users/conan-io/starred{/owner}{/repo}",
			  "subscriptions_url": "https://api.github.com/users/conan-io/subscriptions",
			  "organizations_url": "https://api.github.com/users/conan-io/orgs",
			  "repos_url": "https://api.github.com/users/conan-io/repos",
			  "events_url": "https://api.github.com/users/conan-io/events{/privacy}",
			  "received_events_url": "https://api.github.com/users/conan-io/received_events",
			  "type": "Organization",
			  "site_admin": false
			},
			"html_url": "https://github.com/conan-io/conan-center-index",
			"description": "Recipes for the ConanCenter repository",
			"fork": false,
			"url": "https://api.github.com/repos/conan-io/conan-center-index",
			"forks_url": "https://api.github.com/repos/conan-io/conan-center-index/forks",
			"keys_url": "https://api.github.com/repos/conan-io/conan-center-index/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/conan-io/conan-center-index/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/conan-io/conan-center-index/teams",
			"hooks_url": "https://api.github.com/repos/conan-io/conan-center-index/hooks",
			"issue_events_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/events{/number}",
			"events_url": "https://api.github.com/repos/conan-io/conan-center-index/events",
			"assignees_url": "https://api.github.com/repos/conan-io/conan-center-index/assignees{/user}",
			"branches_url": "https://api.github.com/repos/conan-io/conan-center-index/branches{/branch}",
			"tags_url": "https://api.github.com/repos/conan-io/conan-center-index/tags",
			"blobs_url": "https://api.github.com/repos/conan-io/conan-center-index/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/conan-io/conan-center-index/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/conan-io/conan-center-index/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/conan-io/conan-center-index/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/conan-io/conan-center-index/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/conan-io/conan-center-index/languages",
			"stargazers_url": "https://api.github.com/repos/conan-io/conan-center-index/stargazers",
			"contributors_url": "https://api.github.com/repos/conan-io/conan-center-index/contributors",
			"subscribers_url": "https://api.github.com/repos/conan-io/conan-center-index/subscribers",
			"subscription_url": "https://api.github.com/repos/conan-io/conan-center-index/subscription",
			"commits_url": "https://api.github.com/repos/conan-io/conan-center-index/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/conan-io/conan-center-index/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/conan-io/conan-center-index/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/conan-io/conan-center-index/contents/{+path}",
			"compare_url": "https://api.github.com/repos/conan-io/conan-center-index/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/conan-io/conan-center-index/merges",
			"archive_url": "https://api.github.com/repos/conan-io/conan-center-index/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/conan-io/conan-center-index/downloads",
			"issues_url": "https://api.github.com/repos/conan-io/conan-center-index/issues{/number}",
			"pulls_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/conan-io/conan-center-index/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/conan-io/conan-center-index/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/conan-io/conan-center-index/labels{/name}",
			"releases_url": "https://api.github.com/repos/conan-io/conan-center-index/releases{/id}",
			"deployments_url": "https://api.github.com/repos/conan-io/conan-center-index/deployments",
			"created_at": "2019-08-27T09:43:58Z",
			"updated_at": "2022-08-07T20:52:38Z",
			"pushed_at": "2022-08-08T22:42:54Z",
			"git_url": "git://github.com/conan-io/conan-center-index.git",
			"ssh_url": "git@github.com:conan-io/conan-center-index.git",
			"clone_url": "https://github.com/conan-io/conan-center-index.git",
			"svn_url": "https://github.com/conan-io/conan-center-index",
			"homepage": "https://conan.io/center",
			"size": 34821,
			"stargazers_count": 602,
			"watchers_count": 602,
			"language": "Python",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 998,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 1184,
			"license": {
			  "key": "mit",
			  "name": "MIT License",
			  "spdx_id": "MIT",
			  "url": "https://api.github.com/licenses/mit",
			  "node_id": "MDc6TGljZW5zZTEz"
			},
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
			  "conan",
			  "conan-center",
			  "conan-index",
			  "conan-packages",
			  "conan-recipe",
			  "cpp",
			  "cpp-library",
			  "dependencies",
			  "hacktoberfest",
			  "package-management",
			  "package-manager"
			],
			"visibility": "public",
			"forks": 998,
			"open_issues": 1184,
			"watchers": 602,
			"default_branch": "master"
		  }
		},
		"_links": {
		  "self": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12078"
		  },
		  "html": {
			"href": "https://github.com/conan-io/conan-center-index/pull/12078"
		  },
		  "issue": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/issues/12078"
		  },
		  "comments": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/issues/12078/comments"
		  },
		  "review_comments": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12078/comments"
		  },
		  "review_comment": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/comments{/number}"
		  },
		  "commits": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12078/commits"
		  },
		  "statuses": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/statuses/a21b42a345ce516a7d166101af78f6c5b1e156cf"
		  }
		},
		"author_association": "CONTRIBUTOR",
		"auto_merge": null,
		"active_lock_reason": null,
		"merged": false,
		"mergeable": true,
		"rebaseable": true,
		"mergeable_state": "clean",
		"merged_by": null,
		"comments": 2,
		"review_comments": 0,
		"maintainer_can_modify": true,
		"commits": 2,
		"additions": 138,
		"deletions": 91,
		"changed_files": 6
	  }`)

	err := processLabels(pr.Labels)
	assert.Equal(t, err, nil)
}

func TestProcessLabelsStopped(t *testing.T) {
	pr := parsePullRequestJSON(t, `{
		"url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12055",
		"id": 1017756055,
		"node_id": "PR_kwDODDMJAM48qbmX",
		"html_url": "https://github.com/conan-io/conan-center-index/pull/12055",
		"diff_url": "https://github.com/conan-io/conan-center-index/pull/12055.diff",
		"patch_url": "https://github.com/conan-io/conan-center-index/pull/12055.patch",
		"issue_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/12055",
		"number": 12055,
		"state": "open",
		"locked": false,
		"title": "[sentry-native/xxx] Upgrade to conan v2",
		"user": {
		  "login": "MartinDelille",
		  "id": 879889,
		  "node_id": "MDQ6VXNlcjg3OTg4OQ==",
		  "avatar_url": "https://avatars.githubusercontent.com/u/879889?v=4",
		  "gravatar_id": "",
		  "url": "https://api.github.com/users/MartinDelille",
		  "html_url": "https://github.com/MartinDelille",
		  "followers_url": "https://api.github.com/users/MartinDelille/followers",
		  "following_url": "https://api.github.com/users/MartinDelille/following{/other_user}",
		  "gists_url": "https://api.github.com/users/MartinDelille/gists{/gist_id}",
		  "starred_url": "https://api.github.com/users/MartinDelille/starred{/owner}{/repo}",
		  "subscriptions_url": "https://api.github.com/users/MartinDelille/subscriptions",
		  "organizations_url": "https://api.github.com/users/MartinDelille/orgs",
		  "repos_url": "https://api.github.com/users/MartinDelille/repos",
		  "events_url": "https://api.github.com/users/MartinDelille/events{/privacy}",
		  "received_events_url": "https://api.github.com/users/MartinDelille/received_events",
		  "type": "User",
		  "site_admin": false
		},
		"body": "Work in progress to update sentry-native to conan v2\n---\n\n- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.\n- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.\n- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.\n- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.\n",
		"created_at": "2022-08-04T16:08:20Z",
		"updated_at": "2022-08-04T16:28:57Z",
		"closed_at": null,
		"merged_at": null,
		"merge_commit_sha": "89f86c6deb5b76709cb16ffe5aebb339461f429c",
		"assignee": null,
		"assignees": [
	  
		],
		"requested_reviewers": [
	  
		],
		"requested_teams": [
	  
		],
		"labels": [
		  {
			"id": 1527563132,
			"node_id": "MDU6TGFiZWwxNTI3NTYzMTMy",
			"url": "https://api.github.com/repos/conan-io/conan-center-index/labels/Failed",
			"name": "Failed",
			"color": "ededed",
			"default": false,
			"description": null
		  }
		],
		"milestone": null,
		"draft": false,
		"commits_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12055/commits",
		"review_comments_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12055/comments",
		"review_comment_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/comments{/number}",
		"comments_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/12055/comments",
		"statuses_url": "https://api.github.com/repos/conan-io/conan-center-index/statuses/42afa996c431fc14b033a601f406c8faf26160dd",
		"head": {
		  "label": "MartinDelille:native-v2",
		  "ref": "native-v2",
		  "sha": "42afa996c431fc14b033a601f406c8faf26160dd",
		  "user": {
			"login": "MartinDelille",
			"id": 879889,
			"node_id": "MDQ6VXNlcjg3OTg4OQ==",
			"avatar_url": "https://avatars.githubusercontent.com/u/879889?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/MartinDelille",
			"html_url": "https://github.com/MartinDelille",
			"followers_url": "https://api.github.com/users/MartinDelille/followers",
			"following_url": "https://api.github.com/users/MartinDelille/following{/other_user}",
			"gists_url": "https://api.github.com/users/MartinDelille/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/MartinDelille/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/MartinDelille/subscriptions",
			"organizations_url": "https://api.github.com/users/MartinDelille/orgs",
			"repos_url": "https://api.github.com/users/MartinDelille/repos",
			"events_url": "https://api.github.com/users/MartinDelille/events{/privacy}",
			"received_events_url": "https://api.github.com/users/MartinDelille/received_events",
			"type": "User",
			"site_admin": false
		  },
		  "repo": {
			"id": 287497947,
			"node_id": "MDEwOlJlcG9zaXRvcnkyODc0OTc5NDc=",
			"name": "conan-center-index",
			"full_name": "MartinDelille/conan-center-index",
			"private": false,
			"owner": {
			  "login": "MartinDelille",
			  "id": 879889,
			  "node_id": "MDQ6VXNlcjg3OTg4OQ==",
			  "avatar_url": "https://avatars.githubusercontent.com/u/879889?v=4",
			  "gravatar_id": "",
			  "url": "https://api.github.com/users/MartinDelille",
			  "html_url": "https://github.com/MartinDelille",
			  "followers_url": "https://api.github.com/users/MartinDelille/followers",
			  "following_url": "https://api.github.com/users/MartinDelille/following{/other_user}",
			  "gists_url": "https://api.github.com/users/MartinDelille/gists{/gist_id}",
			  "starred_url": "https://api.github.com/users/MartinDelille/starred{/owner}{/repo}",
			  "subscriptions_url": "https://api.github.com/users/MartinDelille/subscriptions",
			  "organizations_url": "https://api.github.com/users/MartinDelille/orgs",
			  "repos_url": "https://api.github.com/users/MartinDelille/repos",
			  "events_url": "https://api.github.com/users/MartinDelille/events{/privacy}",
			  "received_events_url": "https://api.github.com/users/MartinDelille/received_events",
			  "type": "User",
			  "site_admin": false
			},
			"html_url": "https://github.com/MartinDelille/conan-center-index",
			"description": "Recipes for the ConanCenter repository",
			"fork": true,
			"url": "https://api.github.com/repos/MartinDelille/conan-center-index",
			"forks_url": "https://api.github.com/repos/MartinDelille/conan-center-index/forks",
			"keys_url": "https://api.github.com/repos/MartinDelille/conan-center-index/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/MartinDelille/conan-center-index/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/MartinDelille/conan-center-index/teams",
			"hooks_url": "https://api.github.com/repos/MartinDelille/conan-center-index/hooks",
			"issue_events_url": "https://api.github.com/repos/MartinDelille/conan-center-index/issues/events{/number}",
			"events_url": "https://api.github.com/repos/MartinDelille/conan-center-index/events",
			"assignees_url": "https://api.github.com/repos/MartinDelille/conan-center-index/assignees{/user}",
			"branches_url": "https://api.github.com/repos/MartinDelille/conan-center-index/branches{/branch}",
			"tags_url": "https://api.github.com/repos/MartinDelille/conan-center-index/tags",
			"blobs_url": "https://api.github.com/repos/MartinDelille/conan-center-index/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/MartinDelille/conan-center-index/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/MartinDelille/conan-center-index/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/MartinDelille/conan-center-index/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/MartinDelille/conan-center-index/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/MartinDelille/conan-center-index/languages",
			"stargazers_url": "https://api.github.com/repos/MartinDelille/conan-center-index/stargazers",
			"contributors_url": "https://api.github.com/repos/MartinDelille/conan-center-index/contributors",
			"subscribers_url": "https://api.github.com/repos/MartinDelille/conan-center-index/subscribers",
			"subscription_url": "https://api.github.com/repos/MartinDelille/conan-center-index/subscription",
			"commits_url": "https://api.github.com/repos/MartinDelille/conan-center-index/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/MartinDelille/conan-center-index/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/MartinDelille/conan-center-index/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/MartinDelille/conan-center-index/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/MartinDelille/conan-center-index/contents/{+path}",
			"compare_url": "https://api.github.com/repos/MartinDelille/conan-center-index/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/MartinDelille/conan-center-index/merges",
			"archive_url": "https://api.github.com/repos/MartinDelille/conan-center-index/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/MartinDelille/conan-center-index/downloads",
			"issues_url": "https://api.github.com/repos/MartinDelille/conan-center-index/issues{/number}",
			"pulls_url": "https://api.github.com/repos/MartinDelille/conan-center-index/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/MartinDelille/conan-center-index/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/MartinDelille/conan-center-index/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/MartinDelille/conan-center-index/labels{/name}",
			"releases_url": "https://api.github.com/repos/MartinDelille/conan-center-index/releases{/id}",
			"deployments_url": "https://api.github.com/repos/MartinDelille/conan-center-index/deployments",
			"created_at": "2020-08-14T09:40:06Z",
			"updated_at": "2020-08-14T09:40:08Z",
			"pushed_at": "2022-08-04T16:08:19Z",
			"git_url": "git://github.com/MartinDelille/conan-center-index.git",
			"ssh_url": "git@github.com:MartinDelille/conan-center-index.git",
			"clone_url": "https://github.com/MartinDelille/conan-center-index.git",
			"svn_url": "https://github.com/MartinDelille/conan-center-index",
			"homepage": "https://conan.io/center",
			"size": 34663,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": null,
			"has_issues": false,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": {
			  "key": "mit",
			  "name": "MIT License",
			  "spdx_id": "MIT",
			  "url": "https://api.github.com/licenses/mit",
			  "node_id": "MDc6TGljZW5zZTEz"
			},
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
	  
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master"
		  }
		},
		"base": {
		  "label": "conan-io:master",
		  "ref": "master",
		  "sha": "86a5e31416840b9be0830a38d2f37002c9679948",
		  "user": {
			"login": "conan-io",
			"id": 15212165,
			"node_id": "MDEyOk9yZ2FuaXphdGlvbjE1MjEyMTY1",
			"avatar_url": "https://avatars.githubusercontent.com/u/15212165?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/conan-io",
			"html_url": "https://github.com/conan-io",
			"followers_url": "https://api.github.com/users/conan-io/followers",
			"following_url": "https://api.github.com/users/conan-io/following{/other_user}",
			"gists_url": "https://api.github.com/users/conan-io/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/conan-io/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/conan-io/subscriptions",
			"organizations_url": "https://api.github.com/users/conan-io/orgs",
			"repos_url": "https://api.github.com/users/conan-io/repos",
			"events_url": "https://api.github.com/users/conan-io/events{/privacy}",
			"received_events_url": "https://api.github.com/users/conan-io/received_events",
			"type": "Organization",
			"site_admin": false
		  },
		  "repo": {
			"id": 204671232,
			"node_id": "MDEwOlJlcG9zaXRvcnkyMDQ2NzEyMzI=",
			"name": "conan-center-index",
			"full_name": "conan-io/conan-center-index",
			"private": false,
			"owner": {
			  "login": "conan-io",
			  "id": 15212165,
			  "node_id": "MDEyOk9yZ2FuaXphdGlvbjE1MjEyMTY1",
			  "avatar_url": "https://avatars.githubusercontent.com/u/15212165?v=4",
			  "gravatar_id": "",
			  "url": "https://api.github.com/users/conan-io",
			  "html_url": "https://github.com/conan-io",
			  "followers_url": "https://api.github.com/users/conan-io/followers",
			  "following_url": "https://api.github.com/users/conan-io/following{/other_user}",
			  "gists_url": "https://api.github.com/users/conan-io/gists{/gist_id}",
			  "starred_url": "https://api.github.com/users/conan-io/starred{/owner}{/repo}",
			  "subscriptions_url": "https://api.github.com/users/conan-io/subscriptions",
			  "organizations_url": "https://api.github.com/users/conan-io/orgs",
			  "repos_url": "https://api.github.com/users/conan-io/repos",
			  "events_url": "https://api.github.com/users/conan-io/events{/privacy}",
			  "received_events_url": "https://api.github.com/users/conan-io/received_events",
			  "type": "Organization",
			  "site_admin": false
			},
			"html_url": "https://github.com/conan-io/conan-center-index",
			"description": "Recipes for the ConanCenter repository",
			"fork": false,
			"url": "https://api.github.com/repos/conan-io/conan-center-index",
			"forks_url": "https://api.github.com/repos/conan-io/conan-center-index/forks",
			"keys_url": "https://api.github.com/repos/conan-io/conan-center-index/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/conan-io/conan-center-index/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/conan-io/conan-center-index/teams",
			"hooks_url": "https://api.github.com/repos/conan-io/conan-center-index/hooks",
			"issue_events_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/events{/number}",
			"events_url": "https://api.github.com/repos/conan-io/conan-center-index/events",
			"assignees_url": "https://api.github.com/repos/conan-io/conan-center-index/assignees{/user}",
			"branches_url": "https://api.github.com/repos/conan-io/conan-center-index/branches{/branch}",
			"tags_url": "https://api.github.com/repos/conan-io/conan-center-index/tags",
			"blobs_url": "https://api.github.com/repos/conan-io/conan-center-index/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/conan-io/conan-center-index/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/conan-io/conan-center-index/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/conan-io/conan-center-index/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/conan-io/conan-center-index/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/conan-io/conan-center-index/languages",
			"stargazers_url": "https://api.github.com/repos/conan-io/conan-center-index/stargazers",
			"contributors_url": "https://api.github.com/repos/conan-io/conan-center-index/contributors",
			"subscribers_url": "https://api.github.com/repos/conan-io/conan-center-index/subscribers",
			"subscription_url": "https://api.github.com/repos/conan-io/conan-center-index/subscription",
			"commits_url": "https://api.github.com/repos/conan-io/conan-center-index/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/conan-io/conan-center-index/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/conan-io/conan-center-index/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/conan-io/conan-center-index/contents/{+path}",
			"compare_url": "https://api.github.com/repos/conan-io/conan-center-index/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/conan-io/conan-center-index/merges",
			"archive_url": "https://api.github.com/repos/conan-io/conan-center-index/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/conan-io/conan-center-index/downloads",
			"issues_url": "https://api.github.com/repos/conan-io/conan-center-index/issues{/number}",
			"pulls_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/conan-io/conan-center-index/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/conan-io/conan-center-index/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/conan-io/conan-center-index/labels{/name}",
			"releases_url": "https://api.github.com/repos/conan-io/conan-center-index/releases{/id}",
			"deployments_url": "https://api.github.com/repos/conan-io/conan-center-index/deployments",
			"created_at": "2019-08-27T09:43:58Z",
			"updated_at": "2022-08-07T20:52:38Z",
			"pushed_at": "2022-08-08T22:42:54Z",
			"git_url": "git://github.com/conan-io/conan-center-index.git",
			"ssh_url": "git@github.com:conan-io/conan-center-index.git",
			"clone_url": "https://github.com/conan-io/conan-center-index.git",
			"svn_url": "https://github.com/conan-io/conan-center-index",
			"homepage": "https://conan.io/center",
			"size": 34821,
			"stargazers_count": 602,
			"watchers_count": 602,
			"language": "Python",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 998,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 1184,
			"license": {
			  "key": "mit",
			  "name": "MIT License",
			  "spdx_id": "MIT",
			  "url": "https://api.github.com/licenses/mit",
			  "node_id": "MDc6TGljZW5zZTEz"
			},
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
			  "conan",
			  "conan-center",
			  "conan-index",
			  "conan-packages",
			  "conan-recipe",
			  "cpp",
			  "cpp-library",
			  "dependencies",
			  "hacktoberfest",
			  "package-management",
			  "package-manager"
			],
			"visibility": "public",
			"forks": 998,
			"open_issues": 1184,
			"watchers": 602,
			"default_branch": "master"
		  }
		},
		"_links": {
		  "self": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12055"
		  },
		  "html": {
			"href": "https://github.com/conan-io/conan-center-index/pull/12055"
		  },
		  "issue": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/issues/12055"
		  },
		  "comments": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/issues/12055/comments"
		  },
		  "review_comments": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12055/comments"
		  },
		  "review_comment": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/comments{/number}"
		  },
		  "commits": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12055/commits"
		  },
		  "statuses": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/statuses/42afa996c431fc14b033a601f406c8faf26160dd"
		  }
		},
		"author_association": "CONTRIBUTOR",
		"auto_merge": null,
		"active_lock_reason": null,
		"merged": false,
		"mergeable": true,
		"rebaseable": true,
		"mergeable_state": "unstable",
		"merged_by": null,
		"comments": 2,
		"review_comments": 0,
		"maintainer_can_modify": true,
		"commits": 1,
		"additions": 17,
		"deletions": 15,
		"changed_files": 1
	  }`)

	err := processLabels(pr.Labels)
	assert.EqualError(t, err, ErrStoppedLabel.Error())
}

func TestProcessLabelsBump(t *testing.T) {
	pr := parsePullRequestJSON(t, `{
		"url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12115",
		"id": 1020861683,
		"node_id": "PR_kwDODDMJAM482Rzz",
		"html_url": "https://github.com/conan-io/conan-center-index/pull/12115",
		"diff_url": "https://github.com/conan-io/conan-center-index/pull/12115.diff",
		"patch_url": "https://github.com/conan-io/conan-center-index/pull/12115.patch",
		"issue_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/12115",
		"number": 12115,
		"state": "open",
		"locked": false,
		"title": "sjson-cpp: add version 0.8.3",
		"user": {
		  "login": "prince-chrismc",
		  "id": 16867443,
		  "node_id": "MDQ6VXNlcjE2ODY3NDQz",
		  "avatar_url": "https://avatars.githubusercontent.com/u/16867443?v=4",
		  "gravatar_id": "",
		  "url": "https://api.github.com/users/prince-chrismc",
		  "html_url": "https://github.com/prince-chrismc",
		  "followers_url": "https://api.github.com/users/prince-chrismc/followers",
		  "following_url": "https://api.github.com/users/prince-chrismc/following{/other_user}",
		  "gists_url": "https://api.github.com/users/prince-chrismc/gists{/gist_id}",
		  "starred_url": "https://api.github.com/users/prince-chrismc/starred{/owner}{/repo}",
		  "subscriptions_url": "https://api.github.com/users/prince-chrismc/subscriptions",
		  "organizations_url": "https://api.github.com/users/prince-chrismc/orgs",
		  "repos_url": "https://api.github.com/users/prince-chrismc/repos",
		  "events_url": "https://api.github.com/users/prince-chrismc/events{/privacy}",
		  "received_events_url": "https://api.github.com/users/prince-chrismc/received_events",
		  "type": "User",
		  "site_admin": false
		},
		"body": "Generated and committed by [Conan Center Bot](https://github.com/qchateau/conan-center-bot)\r\nFind more updatable recipes in the [GitHub Pages](https://qchateau.github.io/conan-center-bot/)\r\n\r\nSpecify library name and version:  **lib/1.0**\r\n\r\nThis is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!\r\n\r\n---\r\n\r\n- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.\r\n- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.\r\n- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.\r\n- [ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.\r\n",
		"created_at": "2022-08-08T23:22:22Z",
		"updated_at": "2022-08-08T23:23:41Z",
		"closed_at": null,
		"merged_at": null,
		"merge_commit_sha": "0e7b4521f02ffa3ee0d30d716973f3a9782684cb",
		"assignee": null,
		"assignees": [
	  
		],
		"requested_reviewers": [
	  
		],
		"requested_teams": [
	  
		],
		"labels": [
		  {
			"id": 1983649076,
			"node_id": "MDU6TGFiZWwxOTgzNjQ5MDc2",
			"url": "https://api.github.com/repos/conan-io/conan-center-index/labels/Bump%20version",
			"name": "Bump version",
			"color": "e5fc3a",
			"default": false,
			"description": "PR bumping version without recipe modifications"
		  }
		],
		"milestone": null,
		"draft": false,
		"commits_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12115/commits",
		"review_comments_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12115/comments",
		"review_comment_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/comments{/number}",
		"comments_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/12115/comments",
		"statuses_url": "https://api.github.com/repos/conan-io/conan-center-index/statuses/544e142c147b7cef746fe41cb27c7686a3db69a2",
		"head": {
		  "label": "qchateau:ccb-sjson-cpp-0.8.3",
		  "ref": "ccb-sjson-cpp-0.8.3",
		  "sha": "544e142c147b7cef746fe41cb27c7686a3db69a2",
		  "user": {
			"login": "qchateau",
			"id": 1497628,
			"node_id": "MDQ6VXNlcjE0OTc2Mjg=",
			"avatar_url": "https://avatars.githubusercontent.com/u/1497628?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/qchateau",
			"html_url": "https://github.com/qchateau",
			"followers_url": "https://api.github.com/users/qchateau/followers",
			"following_url": "https://api.github.com/users/qchateau/following{/other_user}",
			"gists_url": "https://api.github.com/users/qchateau/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/qchateau/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/qchateau/subscriptions",
			"organizations_url": "https://api.github.com/users/qchateau/orgs",
			"repos_url": "https://api.github.com/users/qchateau/repos",
			"events_url": "https://api.github.com/users/qchateau/events{/privacy}",
			"received_events_url": "https://api.github.com/users/qchateau/received_events",
			"type": "User",
			"site_admin": false
		  },
		  "repo": {
			"id": 240522528,
			"node_id": "MDEwOlJlcG9zaXRvcnkyNDA1MjI1Mjg=",
			"name": "conan-center-index",
			"full_name": "qchateau/conan-center-index",
			"private": false,
			"owner": {
			  "login": "qchateau",
			  "id": 1497628,
			  "node_id": "MDQ6VXNlcjE0OTc2Mjg=",
			  "avatar_url": "https://avatars.githubusercontent.com/u/1497628?v=4",
			  "gravatar_id": "",
			  "url": "https://api.github.com/users/qchateau",
			  "html_url": "https://github.com/qchateau",
			  "followers_url": "https://api.github.com/users/qchateau/followers",
			  "following_url": "https://api.github.com/users/qchateau/following{/other_user}",
			  "gists_url": "https://api.github.com/users/qchateau/gists{/gist_id}",
			  "starred_url": "https://api.github.com/users/qchateau/starred{/owner}{/repo}",
			  "subscriptions_url": "https://api.github.com/users/qchateau/subscriptions",
			  "organizations_url": "https://api.github.com/users/qchateau/orgs",
			  "repos_url": "https://api.github.com/users/qchateau/repos",
			  "events_url": "https://api.github.com/users/qchateau/events{/privacy}",
			  "received_events_url": "https://api.github.com/users/qchateau/received_events",
			  "type": "User",
			  "site_admin": false
			},
			"html_url": "https://github.com/qchateau/conan-center-index",
			"description": "Recipes for the ConanCenter repository",
			"fork": true,
			"url": "https://api.github.com/repos/qchateau/conan-center-index",
			"forks_url": "https://api.github.com/repos/qchateau/conan-center-index/forks",
			"keys_url": "https://api.github.com/repos/qchateau/conan-center-index/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/qchateau/conan-center-index/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/qchateau/conan-center-index/teams",
			"hooks_url": "https://api.github.com/repos/qchateau/conan-center-index/hooks",
			"issue_events_url": "https://api.github.com/repos/qchateau/conan-center-index/issues/events{/number}",
			"events_url": "https://api.github.com/repos/qchateau/conan-center-index/events",
			"assignees_url": "https://api.github.com/repos/qchateau/conan-center-index/assignees{/user}",
			"branches_url": "https://api.github.com/repos/qchateau/conan-center-index/branches{/branch}",
			"tags_url": "https://api.github.com/repos/qchateau/conan-center-index/tags",
			"blobs_url": "https://api.github.com/repos/qchateau/conan-center-index/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/qchateau/conan-center-index/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/qchateau/conan-center-index/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/qchateau/conan-center-index/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/qchateau/conan-center-index/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/qchateau/conan-center-index/languages",
			"stargazers_url": "https://api.github.com/repos/qchateau/conan-center-index/stargazers",
			"contributors_url": "https://api.github.com/repos/qchateau/conan-center-index/contributors",
			"subscribers_url": "https://api.github.com/repos/qchateau/conan-center-index/subscribers",
			"subscription_url": "https://api.github.com/repos/qchateau/conan-center-index/subscription",
			"commits_url": "https://api.github.com/repos/qchateau/conan-center-index/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/qchateau/conan-center-index/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/qchateau/conan-center-index/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/qchateau/conan-center-index/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/qchateau/conan-center-index/contents/{+path}",
			"compare_url": "https://api.github.com/repos/qchateau/conan-center-index/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/qchateau/conan-center-index/merges",
			"archive_url": "https://api.github.com/repos/qchateau/conan-center-index/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/qchateau/conan-center-index/downloads",
			"issues_url": "https://api.github.com/repos/qchateau/conan-center-index/issues{/number}",
			"pulls_url": "https://api.github.com/repos/qchateau/conan-center-index/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/qchateau/conan-center-index/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/qchateau/conan-center-index/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/qchateau/conan-center-index/labels{/name}",
			"releases_url": "https://api.github.com/repos/qchateau/conan-center-index/releases{/id}",
			"deployments_url": "https://api.github.com/repos/qchateau/conan-center-index/deployments",
			"created_at": "2020-02-14T14:09:26Z",
			"updated_at": "2020-06-13T18:49:20Z",
			"pushed_at": "2022-08-08T18:52:11Z",
			"git_url": "git://github.com/qchateau/conan-center-index.git",
			"ssh_url": "git@github.com:qchateau/conan-center-index.git",
			"clone_url": "https://github.com/qchateau/conan-center-index.git",
			"svn_url": "https://github.com/qchateau/conan-center-index",
			"homepage": "https://conan.io/center",
			"size": 35667,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": "Python",
			"has_issues": false,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": {
			  "key": "mit",
			  "name": "MIT License",
			  "spdx_id": "MIT",
			  "url": "https://api.github.com/licenses/mit",
			  "node_id": "MDc6TGljZW5zZTEz"
			},
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
	  
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master"
		  }
		},
		"base": {
		  "label": "conan-io:master",
		  "ref": "master",
		  "sha": "3fba379f79d7e48df59808b45d7614bab0d94620",
		  "user": {
			"login": "conan-io",
			"id": 15212165,
			"node_id": "MDEyOk9yZ2FuaXphdGlvbjE1MjEyMTY1",
			"avatar_url": "https://avatars.githubusercontent.com/u/15212165?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/conan-io",
			"html_url": "https://github.com/conan-io",
			"followers_url": "https://api.github.com/users/conan-io/followers",
			"following_url": "https://api.github.com/users/conan-io/following{/other_user}",
			"gists_url": "https://api.github.com/users/conan-io/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/conan-io/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/conan-io/subscriptions",
			"organizations_url": "https://api.github.com/users/conan-io/orgs",
			"repos_url": "https://api.github.com/users/conan-io/repos",
			"events_url": "https://api.github.com/users/conan-io/events{/privacy}",
			"received_events_url": "https://api.github.com/users/conan-io/received_events",
			"type": "Organization",
			"site_admin": false
		  },
		  "repo": {
			"id": 204671232,
			"node_id": "MDEwOlJlcG9zaXRvcnkyMDQ2NzEyMzI=",
			"name": "conan-center-index",
			"full_name": "conan-io/conan-center-index",
			"private": false,
			"owner": {
			  "login": "conan-io",
			  "id": 15212165,
			  "node_id": "MDEyOk9yZ2FuaXphdGlvbjE1MjEyMTY1",
			  "avatar_url": "https://avatars.githubusercontent.com/u/15212165?v=4",
			  "gravatar_id": "",
			  "url": "https://api.github.com/users/conan-io",
			  "html_url": "https://github.com/conan-io",
			  "followers_url": "https://api.github.com/users/conan-io/followers",
			  "following_url": "https://api.github.com/users/conan-io/following{/other_user}",
			  "gists_url": "https://api.github.com/users/conan-io/gists{/gist_id}",
			  "starred_url": "https://api.github.com/users/conan-io/starred{/owner}{/repo}",
			  "subscriptions_url": "https://api.github.com/users/conan-io/subscriptions",
			  "organizations_url": "https://api.github.com/users/conan-io/orgs",
			  "repos_url": "https://api.github.com/users/conan-io/repos",
			  "events_url": "https://api.github.com/users/conan-io/events{/privacy}",
			  "received_events_url": "https://api.github.com/users/conan-io/received_events",
			  "type": "Organization",
			  "site_admin": false
			},
			"html_url": "https://github.com/conan-io/conan-center-index",
			"description": "Recipes for the ConanCenter repository",
			"fork": false,
			"url": "https://api.github.com/repos/conan-io/conan-center-index",
			"forks_url": "https://api.github.com/repos/conan-io/conan-center-index/forks",
			"keys_url": "https://api.github.com/repos/conan-io/conan-center-index/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/conan-io/conan-center-index/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/conan-io/conan-center-index/teams",
			"hooks_url": "https://api.github.com/repos/conan-io/conan-center-index/hooks",
			"issue_events_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/events{/number}",
			"events_url": "https://api.github.com/repos/conan-io/conan-center-index/events",
			"assignees_url": "https://api.github.com/repos/conan-io/conan-center-index/assignees{/user}",
			"branches_url": "https://api.github.com/repos/conan-io/conan-center-index/branches{/branch}",
			"tags_url": "https://api.github.com/repos/conan-io/conan-center-index/tags",
			"blobs_url": "https://api.github.com/repos/conan-io/conan-center-index/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/conan-io/conan-center-index/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/conan-io/conan-center-index/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/conan-io/conan-center-index/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/conan-io/conan-center-index/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/conan-io/conan-center-index/languages",
			"stargazers_url": "https://api.github.com/repos/conan-io/conan-center-index/stargazers",
			"contributors_url": "https://api.github.com/repos/conan-io/conan-center-index/contributors",
			"subscribers_url": "https://api.github.com/repos/conan-io/conan-center-index/subscribers",
			"subscription_url": "https://api.github.com/repos/conan-io/conan-center-index/subscription",
			"commits_url": "https://api.github.com/repos/conan-io/conan-center-index/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/conan-io/conan-center-index/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/conan-io/conan-center-index/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/conan-io/conan-center-index/contents/{+path}",
			"compare_url": "https://api.github.com/repos/conan-io/conan-center-index/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/conan-io/conan-center-index/merges",
			"archive_url": "https://api.github.com/repos/conan-io/conan-center-index/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/conan-io/conan-center-index/downloads",
			"issues_url": "https://api.github.com/repos/conan-io/conan-center-index/issues{/number}",
			"pulls_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/conan-io/conan-center-index/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/conan-io/conan-center-index/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/conan-io/conan-center-index/labels{/name}",
			"releases_url": "https://api.github.com/repos/conan-io/conan-center-index/releases{/id}",
			"deployments_url": "https://api.github.com/repos/conan-io/conan-center-index/deployments",
			"created_at": "2019-08-27T09:43:58Z",
			"updated_at": "2022-08-07T20:52:38Z",
			"pushed_at": "2022-08-08T23:22:23Z",
			"git_url": "git://github.com/conan-io/conan-center-index.git",
			"ssh_url": "git@github.com:conan-io/conan-center-index.git",
			"clone_url": "https://github.com/conan-io/conan-center-index.git",
			"svn_url": "https://github.com/conan-io/conan-center-index",
			"homepage": "https://conan.io/center",
			"size": 34821,
			"stargazers_count": 602,
			"watchers_count": 602,
			"language": "Python",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 998,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 1186,
			"license": {
			  "key": "mit",
			  "name": "MIT License",
			  "spdx_id": "MIT",
			  "url": "https://api.github.com/licenses/mit",
			  "node_id": "MDc6TGljZW5zZTEz"
			},
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
			  "conan",
			  "conan-center",
			  "conan-index",
			  "conan-packages",
			  "conan-recipe",
			  "cpp",
			  "cpp-library",
			  "dependencies",
			  "hacktoberfest",
			  "package-management",
			  "package-manager"
			],
			"visibility": "public",
			"forks": 998,
			"open_issues": 1186,
			"watchers": 602,
			"default_branch": "master"
		  }
		},
		"_links": {
		  "self": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12115"
		  },
		  "html": {
			"href": "https://github.com/conan-io/conan-center-index/pull/12115"
		  },
		  "issue": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/issues/12115"
		  },
		  "comments": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/issues/12115/comments"
		  },
		  "review_comments": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12115/comments"
		  },
		  "review_comment": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/comments{/number}"
		  },
		  "commits": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12115/commits"
		  },
		  "statuses": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/statuses/544e142c147b7cef746fe41cb27c7686a3db69a2"
		  }
		},
		"author_association": "CONTRIBUTOR",
		"auto_merge": null,
		"active_lock_reason": null,
		"merged": false,
		"mergeable": true,
		"rebaseable": true,
		"mergeable_state": "unstable",
		"merged_by": null,
		"comments": 0,
		"review_comments": 0,
		"maintainer_can_modify": true,
		"commits": 1,
		"additions": 5,
		"deletions": 0,
		"changed_files": 2
	  }`)

	err := processLabels(pr.Labels)
	assert.EqualError(t, err, ErrBumpLabel.Error())
}

func TestProcessLabelsNoApproval(t *testing.T) {
	pr := parsePullRequestJSON(t, `{
		"url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12066",
		"id": 1018548334,
		"node_id": "PR_kwDODDMJAM48tdBu",
		"html_url": "https://github.com/conan-io/conan-center-index/pull/12066",
		"diff_url": "https://github.com/conan-io/conan-center-index/pull/12066.diff",
		"patch_url": "https://github.com/conan-io/conan-center-index/pull/12066.patch",
		"issue_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/12066",
		"number": 12066,
		"state": "open",
		"locked": false,
		"title": "log4cplus: add thread_pool option",
		"user": {
		  "login": "mvoelkle-cern",
		  "id": 54059203,
		  "node_id": "MDQ6VXNlcjU0MDU5MjAz",
		  "avatar_url": "https://avatars.githubusercontent.com/u/54059203?v=4",
		  "gravatar_id": "",
		  "url": "https://api.github.com/users/mvoelkle-cern",
		  "html_url": "https://github.com/mvoelkle-cern",
		  "followers_url": "https://api.github.com/users/mvoelkle-cern/followers",
		  "following_url": "https://api.github.com/users/mvoelkle-cern/following{/other_user}",
		  "gists_url": "https://api.github.com/users/mvoelkle-cern/gists{/gist_id}",
		  "starred_url": "https://api.github.com/users/mvoelkle-cern/starred{/owner}{/repo}",
		  "subscriptions_url": "https://api.github.com/users/mvoelkle-cern/subscriptions",
		  "organizations_url": "https://api.github.com/users/mvoelkle-cern/orgs",
		  "repos_url": "https://api.github.com/users/mvoelkle-cern/repos",
		  "events_url": "https://api.github.com/users/mvoelkle-cern/events{/privacy}",
		  "received_events_url": "https://api.github.com/users/mvoelkle-cern/received_events",
		  "type": "User",
		  "site_admin": false
		},
		"body": "log4cplus all versions\r\n\r\nAs we need to disable the thread pool feature on Windows, I'm adding an option to do so.\r\n\r\n---\r\n\r\n- [x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.\r\n- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.\r\n- [x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.\r\n- [x] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.\r\n",
		"created_at": "2022-08-05T11:00:47Z",
		"updated_at": "2022-08-05T16:14:48Z",
		"closed_at": null,
		"merged_at": null,
		"merge_commit_sha": "9a205a7ca79fa88a70c95db6bd87cb74b8d908b5",
		"assignee": null,
		"assignees": [
	  
		],
		"requested_reviewers": [
	  
		],
		"requested_teams": [
	  
		],
		"labels": [
		  {
			"id": 3464096826,
			"node_id": "LA_kwDODDMJAM7Oeew6",
			"url": "https://api.github.com/repos/conan-io/conan-center-index/labels/User-approval%20pending",
			"name": "User-approval pending",
			"color": "ededed",
			"default": false,
			"description": null
		  }
		],
		"milestone": null,
		"draft": false,
		"commits_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12066/commits",
		"review_comments_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12066/comments",
		"review_comment_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls/comments{/number}",
		"comments_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/12066/comments",
		"statuses_url": "https://api.github.com/repos/conan-io/conan-center-index/statuses/04a9e02f2487ed60e2bc1f4e937089694c643dfd",
		"head": {
		  "label": "mvoelkle-cern:package/log4cplus_thread_pool",
		  "ref": "package/log4cplus_thread_pool",
		  "sha": "04a9e02f2487ed60e2bc1f4e937089694c643dfd",
		  "user": {
			"login": "mvoelkle-cern",
			"id": 54059203,
			"node_id": "MDQ6VXNlcjU0MDU5MjAz",
			"avatar_url": "https://avatars.githubusercontent.com/u/54059203?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mvoelkle-cern",
			"html_url": "https://github.com/mvoelkle-cern",
			"followers_url": "https://api.github.com/users/mvoelkle-cern/followers",
			"following_url": "https://api.github.com/users/mvoelkle-cern/following{/other_user}",
			"gists_url": "https://api.github.com/users/mvoelkle-cern/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mvoelkle-cern/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mvoelkle-cern/subscriptions",
			"organizations_url": "https://api.github.com/users/mvoelkle-cern/orgs",
			"repos_url": "https://api.github.com/users/mvoelkle-cern/repos",
			"events_url": "https://api.github.com/users/mvoelkle-cern/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mvoelkle-cern/received_events",
			"type": "User",
			"site_admin": false
		  },
		  "repo": {
			"id": 521589353,
			"node_id": "R_kgDOHxbSaQ",
			"name": "conan-center-index",
			"full_name": "mvoelkle-cern/conan-center-index",
			"private": false,
			"owner": {
			  "login": "mvoelkle-cern",
			  "id": 54059203,
			  "node_id": "MDQ6VXNlcjU0MDU5MjAz",
			  "avatar_url": "https://avatars.githubusercontent.com/u/54059203?v=4",
			  "gravatar_id": "",
			  "url": "https://api.github.com/users/mvoelkle-cern",
			  "html_url": "https://github.com/mvoelkle-cern",
			  "followers_url": "https://api.github.com/users/mvoelkle-cern/followers",
			  "following_url": "https://api.github.com/users/mvoelkle-cern/following{/other_user}",
			  "gists_url": "https://api.github.com/users/mvoelkle-cern/gists{/gist_id}",
			  "starred_url": "https://api.github.com/users/mvoelkle-cern/starred{/owner}{/repo}",
			  "subscriptions_url": "https://api.github.com/users/mvoelkle-cern/subscriptions",
			  "organizations_url": "https://api.github.com/users/mvoelkle-cern/orgs",
			  "repos_url": "https://api.github.com/users/mvoelkle-cern/repos",
			  "events_url": "https://api.github.com/users/mvoelkle-cern/events{/privacy}",
			  "received_events_url": "https://api.github.com/users/mvoelkle-cern/received_events",
			  "type": "User",
			  "site_admin": false
			},
			"html_url": "https://github.com/mvoelkle-cern/conan-center-index",
			"description": "Recipes for the ConanCenter repository",
			"fork": true,
			"url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index",
			"forks_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/forks",
			"keys_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/teams",
			"hooks_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/hooks",
			"issue_events_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/issues/events{/number}",
			"events_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/events",
			"assignees_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/assignees{/user}",
			"branches_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/branches{/branch}",
			"tags_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/tags",
			"blobs_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/languages",
			"stargazers_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/stargazers",
			"contributors_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/contributors",
			"subscribers_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/subscribers",
			"subscription_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/subscription",
			"commits_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/contents/{+path}",
			"compare_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/merges",
			"archive_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/downloads",
			"issues_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/issues{/number}",
			"pulls_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/labels{/name}",
			"releases_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/releases{/id}",
			"deployments_url": "https://api.github.com/repos/mvoelkle-cern/conan-center-index/deployments",
			"created_at": "2022-08-05T10:04:57Z",
			"updated_at": "2022-08-05T10:55:10Z",
			"pushed_at": "2022-08-05T12:08:34Z",
			"git_url": "git://github.com/mvoelkle-cern/conan-center-index.git",
			"ssh_url": "git@github.com:mvoelkle-cern/conan-center-index.git",
			"clone_url": "https://github.com/mvoelkle-cern/conan-center-index.git",
			"svn_url": "https://github.com/mvoelkle-cern/conan-center-index",
			"homepage": "https://conan.io/center",
			"size": 34634,
			"stargazers_count": 0,
			"watchers_count": 0,
			"language": "Python",
			"has_issues": false,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 0,
			"license": {
			  "key": "mit",
			  "name": "MIT License",
			  "spdx_id": "MIT",
			  "url": "https://api.github.com/licenses/mit",
			  "node_id": "MDc6TGljZW5zZTEz"
			},
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
	  
			],
			"visibility": "public",
			"forks": 0,
			"open_issues": 0,
			"watchers": 0,
			"default_branch": "master"
		  }
		},
		"base": {
		  "label": "conan-io:master",
		  "ref": "master",
		  "sha": "7c3f81b16596a01e9d4785d98f996dd367901524",
		  "user": {
			"login": "conan-io",
			"id": 15212165,
			"node_id": "MDEyOk9yZ2FuaXphdGlvbjE1MjEyMTY1",
			"avatar_url": "https://avatars.githubusercontent.com/u/15212165?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/conan-io",
			"html_url": "https://github.com/conan-io",
			"followers_url": "https://api.github.com/users/conan-io/followers",
			"following_url": "https://api.github.com/users/conan-io/following{/other_user}",
			"gists_url": "https://api.github.com/users/conan-io/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/conan-io/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/conan-io/subscriptions",
			"organizations_url": "https://api.github.com/users/conan-io/orgs",
			"repos_url": "https://api.github.com/users/conan-io/repos",
			"events_url": "https://api.github.com/users/conan-io/events{/privacy}",
			"received_events_url": "https://api.github.com/users/conan-io/received_events",
			"type": "Organization",
			"site_admin": false
		  },
		  "repo": {
			"id": 204671232,
			"node_id": "MDEwOlJlcG9zaXRvcnkyMDQ2NzEyMzI=",
			"name": "conan-center-index",
			"full_name": "conan-io/conan-center-index",
			"private": false,
			"owner": {
			  "login": "conan-io",
			  "id": 15212165,
			  "node_id": "MDEyOk9yZ2FuaXphdGlvbjE1MjEyMTY1",
			  "avatar_url": "https://avatars.githubusercontent.com/u/15212165?v=4",
			  "gravatar_id": "",
			  "url": "https://api.github.com/users/conan-io",
			  "html_url": "https://github.com/conan-io",
			  "followers_url": "https://api.github.com/users/conan-io/followers",
			  "following_url": "https://api.github.com/users/conan-io/following{/other_user}",
			  "gists_url": "https://api.github.com/users/conan-io/gists{/gist_id}",
			  "starred_url": "https://api.github.com/users/conan-io/starred{/owner}{/repo}",
			  "subscriptions_url": "https://api.github.com/users/conan-io/subscriptions",
			  "organizations_url": "https://api.github.com/users/conan-io/orgs",
			  "repos_url": "https://api.github.com/users/conan-io/repos",
			  "events_url": "https://api.github.com/users/conan-io/events{/privacy}",
			  "received_events_url": "https://api.github.com/users/conan-io/received_events",
			  "type": "Organization",
			  "site_admin": false
			},
			"html_url": "https://github.com/conan-io/conan-center-index",
			"description": "Recipes for the ConanCenter repository",
			"fork": false,
			"url": "https://api.github.com/repos/conan-io/conan-center-index",
			"forks_url": "https://api.github.com/repos/conan-io/conan-center-index/forks",
			"keys_url": "https://api.github.com/repos/conan-io/conan-center-index/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/conan-io/conan-center-index/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/conan-io/conan-center-index/teams",
			"hooks_url": "https://api.github.com/repos/conan-io/conan-center-index/hooks",
			"issue_events_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/events{/number}",
			"events_url": "https://api.github.com/repos/conan-io/conan-center-index/events",
			"assignees_url": "https://api.github.com/repos/conan-io/conan-center-index/assignees{/user}",
			"branches_url": "https://api.github.com/repos/conan-io/conan-center-index/branches{/branch}",
			"tags_url": "https://api.github.com/repos/conan-io/conan-center-index/tags",
			"blobs_url": "https://api.github.com/repos/conan-io/conan-center-index/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/conan-io/conan-center-index/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/conan-io/conan-center-index/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/conan-io/conan-center-index/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/conan-io/conan-center-index/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/conan-io/conan-center-index/languages",
			"stargazers_url": "https://api.github.com/repos/conan-io/conan-center-index/stargazers",
			"contributors_url": "https://api.github.com/repos/conan-io/conan-center-index/contributors",
			"subscribers_url": "https://api.github.com/repos/conan-io/conan-center-index/subscribers",
			"subscription_url": "https://api.github.com/repos/conan-io/conan-center-index/subscription",
			"commits_url": "https://api.github.com/repos/conan-io/conan-center-index/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/conan-io/conan-center-index/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/conan-io/conan-center-index/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/conan-io/conan-center-index/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/conan-io/conan-center-index/contents/{+path}",
			"compare_url": "https://api.github.com/repos/conan-io/conan-center-index/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/conan-io/conan-center-index/merges",
			"archive_url": "https://api.github.com/repos/conan-io/conan-center-index/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/conan-io/conan-center-index/downloads",
			"issues_url": "https://api.github.com/repos/conan-io/conan-center-index/issues{/number}",
			"pulls_url": "https://api.github.com/repos/conan-io/conan-center-index/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/conan-io/conan-center-index/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/conan-io/conan-center-index/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/conan-io/conan-center-index/labels{/name}",
			"releases_url": "https://api.github.com/repos/conan-io/conan-center-index/releases{/id}",
			"deployments_url": "https://api.github.com/repos/conan-io/conan-center-index/deployments",
			"created_at": "2019-08-27T09:43:58Z",
			"updated_at": "2022-08-07T20:52:38Z",
			"pushed_at": "2022-08-08T23:22:23Z",
			"git_url": "git://github.com/conan-io/conan-center-index.git",
			"ssh_url": "git@github.com:conan-io/conan-center-index.git",
			"clone_url": "https://github.com/conan-io/conan-center-index.git",
			"svn_url": "https://github.com/conan-io/conan-center-index",
			"homepage": "https://conan.io/center",
			"size": 34821,
			"stargazers_count": 602,
			"watchers_count": 602,
			"language": "Python",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 998,
			"mirror_url": null,
			"archived": false,
			"disabled": false,
			"open_issues_count": 1186,
			"license": {
			  "key": "mit",
			  "name": "MIT License",
			  "spdx_id": "MIT",
			  "url": "https://api.github.com/licenses/mit",
			  "node_id": "MDc6TGljZW5zZTEz"
			},
			"allow_forking": true,
			"is_template": false,
			"web_commit_signoff_required": false,
			"topics": [
			  "conan",
			  "conan-center",
			  "conan-index",
			  "conan-packages",
			  "conan-recipe",
			  "cpp",
			  "cpp-library",
			  "dependencies",
			  "hacktoberfest",
			  "package-management",
			  "package-manager"
			],
			"visibility": "public",
			"forks": 998,
			"open_issues": 1186,
			"watchers": 602,
			"default_branch": "master"
		  }
		},
		"_links": {
		  "self": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12066"
		  },
		  "html": {
			"href": "https://github.com/conan-io/conan-center-index/pull/12066"
		  },
		  "issue": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/issues/12066"
		  },
		  "comments": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/issues/12066/comments"
		  },
		  "review_comments": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12066/comments"
		  },
		  "review_comment": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/comments{/number}"
		  },
		  "commits": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/pulls/12066/commits"
		  },
		  "statuses": {
			"href": "https://api.github.com/repos/conan-io/conan-center-index/statuses/04a9e02f2487ed60e2bc1f4e937089694c643dfd"
		  }
		},
		"author_association": "NONE",
		"auto_merge": null,
		"active_lock_reason": null,
		"merged": false,
		"mergeable": true,
		"rebaseable": true,
		"mergeable_state": "unstable",
		"merged_by": null,
		"comments": 3,
		"review_comments": 1,
		"maintainer_can_modify": true,
		"commits": 2,
		"additions": 8,
		"deletions": 4,
		"changed_files": 1
	  }`)

	err := processLabels(pr.Labels)
	assert.Equal(t, err, nil)
}

func parsePullRequestFilesJSON(t *testing.T, str string) []*CommitFile {
	var files []*CommitFile

	if err := json.Unmarshal([]byte(str), &files); err != nil {
		t.Fatal("Unable to parse JSON")
	}

	return files
}

func TestProcessChangedFiles(t *testing.T) {
	files := parsePullRequestFilesJSON(t, `[
    {
      "sha": "6761b154e37b6cdeac8a4117c420b3a3ab1380cc",
      "filename": "recipes/jfalcou-eve/all/conanfile.py",
      "status": "modified",
      "additions": 1,
      "deletions": 3,
      "changes": 4,
      "blob_url": "https://github.com/conan-io/conan-center-index/blob/8a13d1497e84d700ffe2a8560a0d7a8c9e2a64ee/recipes%2Fjfalcou-eve%2Fall%2Fconanfile.py",
      "raw_url": "https://github.com/conan-io/conan-center-index/raw/8a13d1497e84d700ffe2a8560a0d7a8c9e2a64ee/recipes%2Fjfalcou-eve%2Fall%2Fconanfile.py",
      "contents_url": "https://api.github.com/repos/conan-io/conan-center-index/contents/recipes%2Fjfalcou-eve%2Fall%2Fconanfile.py?ref=8a13d1497e84d700ffe2a8560a0d7a8c9e2a64ee",
      "patch": "@@ -35,7 +35,7 @@ def _compilers_minimum_version(self):\n                 \"Visual Studio\": \"16.9\",\n                 \"msvc\": \"1928\",\n                 \"clang\": \"13\",\n-                \"apple-clang\": \"13\"}\n+                \"apple-clang\": \"14\"}\n \n     def configure(self):\n         version = Version(self.version.strip(\"v\"))\n@@ -53,8 +53,6 @@ def validate(self):\n             check_min_cppstd(self, self._min_cppstd)\n         if is_msvc(self):\n             raise ConanInvalidConfiguration(\"EVE does not support MSVC yet (https://github.com/jfalcou/eve/issues/1022).\")\n-        if self.settings.compiler == \"apple-clang\":\n-            raise ConanInvalidConfiguration(\"EVE does not support apple Clang due to an incomplete libcpp.\")\n \n         def lazy_lt_semver(v1, v2):\n             lv1 = [int(v) for v in v1.split(\".\")]"
    }
  ]`)

	_, err := processChangedFiles(files)
	assert.Equal(t, err, nil)
}
